name: Bump version and tag

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    name: Create Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          
      - name: Check if tag exists
        run: |
          if git rev-parse v1.0 >/dev/null 2>&1; then
            echo "Tag v1.0 already exists. Handling accordingly."
            # Add the handling for existing tag here
            # For example: 
            # git tag --delete v1.0
            # git push origin :refs/tags/v1.0
          else
            echo "Tag v1.0 doesn't exist. Continuing with the release creation."
          fi
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0
          release_name: "Release 1.0"
