name: example workflow
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      content: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build with webpack
        run: npm run build
      - name: Run tests
        run: npm test
