name: example workflow
on: [push]

# Define task like building, testing, deploying
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: npm install
    - name: Build with webpack
      run: npm run build
